[build]
  publish = "./"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# Simple SPA handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[dev]
  command = "npm start"
  port = 3000
  publish = "./" 